export enum Path {
  Applications = '/applications',
  Home = '/home',
  HomeDashboard = '/home/dashboard',
  Thread = '/home/[id]',
  Database = '/database',
  Workflow = '/workflow',
  Tools = '/tools',
  Modeling = '/modeling',
  Onboarding = '/setup',
  OnboardingConnection = '/setup/connection',
  OnboardingModels = '/setup/models',
  OnboardingRelationships = '/setup/relationships',
  Knowledge = '/knowledge',
  KnowledgeQuestionSQLPairs = '/knowledge/question-sql-pairs',
  KnowledgeInstructions = '/knowledge/instructions',
  APIManagement = '/api-management',
  APIManagementHistory = '/api-management/history',
}
