import Link from 'next/link';
import { useRouter } from 'next/router';
import { useMemo, useState } from 'react';
import {
  Alert,
  Button,
  Col,
  Row,
  Space,
  Spin,
  Steps,
  Tag,
  Typography,
  message,
} from 'antd';
import ApiOutlined from '@ant-design/icons/ApiOutlined';
import ArrowLeftOutlined from '@ant-design/icons/ArrowLeftOutlined';
import CheckCircleOutlined from '@ant-design/icons/CheckCircleOutlined';
import ConsoleSqlOutlined from '@ant-design/icons/ConsoleSqlOutlined';
import DatabaseOutlined from '@ant-design/icons/DatabaseOutlined';
import EditOutlined from '@ant-design/icons/EditOutlined';
import FunctionOutlined from '@ant-design/icons/FunctionOutlined';
import KeyOutlined from '@ant-design/icons/KeyOutlined';
import PlusOutlined from '@ant-design/icons/PlusOutlined';
import RocketOutlined from '@ant-design/icons/RocketOutlined';
import TableOutlined from '@ant-design/icons/TableOutlined';
import styled from 'styled-components';
import {
  ConstructCard,
  ConstructEmpty,
  ConstructGrid,
  ConstructLayout,
  ConstructToolbar,
  StatusTag,
} from '@/components/construct/ConstructLayout';
import ConnectDataSource from '@/components/pages/setup/ConnectDataSource';
import DefineRelations, {
  SelectedRecommendRelations,
} from '@/components/pages/setup/DefineRelations';
import SelectModels from '@/components/pages/setup/SelectModels';
import Starter from '@/components/pages/setup/Starter';
import { useDiagramQuery } from '@/apollo/client/graphql/diagram.generated';
import { useDeployStatusQuery } from '@/apollo/client/graphql/deploy.generated';
import {
  useAutoGeneratedRelationsQuery,
  useListDataSourceTablesQuery,
  useSaveDataSourceMutation,
  useSaveRelationsMutation,
  useSaveTablesMutation,
  useSchemaChangeQuery,
  useUpdateDataSourceMutation,
} from '@/apollo/client/graphql/dataSource.generated';
import { DIAGRAM } from '@/apollo/client/graphql/diagram';
import { LIST_MODELS } from '@/apollo/client/graphql/model';
import { useGetSettingsQuery } from '@/apollo/client/graphql/settings.generated';
import {
  DataSourceName,
  RelationInput,
} from '@/apollo/client/graphql/__types__';
import { DATA_SOURCES, FORM_MODE, Path } from '@/utils/enum';
import {
  transformFormToProperties,
  transformPropertiesToForm,
} from '@/hooks/useSetupConnectionDataSource';
import { parseGraphQLError } from '@/utils/errorHandler';

const { Paragraph, Text } = Typography;

type EditorStep =
  | 'source'
  | 'tables'
  | 'access'
  | 'modeling'
  | 'knowledge'
  | 'publish'
  | 'ask';

const editorSteps: Array<{
  key: EditorStep;
  title: string;
  icon: React.ReactNode;
}> = [
  { key: 'source', title: 'Data source', icon: <DatabaseOutlined /> },
  { key: 'tables', title: 'Tables', icon: <TableOutlined /> },
  { key: 'access', title: 'Access', icon: <KeyOutlined /> },
  { key: 'modeling', title: 'Modeling', icon: <ConsoleSqlOutlined /> },
  { key: 'knowledge', title: 'Knowledge', icon: <FunctionOutlined /> },
  { key: 'publish', title: 'Publish', icon: <RocketOutlined /> },
  { key: 'ask', title: 'Ask', icon: <CheckCircleOutlined /> },
];

const editorStepKeys = editorSteps.map((step) => step.key);

const ProductRow = styled.div`
  display: grid;
  grid-template-columns: minmax(220px, 1fr) 132px 148px 132px 148px;
  align-items: center;
  gap: 16px;
  padding: 14px 16px;
  border: 1px solid rgba(226, 232, 240, 0.92);
  border-radius: 8px;
  background: rgba(255, 255, 255, 0.88);
  box-shadow: 0 8px 26px rgba(15, 23, 42, 0.05);

  @media (max-width: 980px) {
    grid-template-columns: 1fr;
  }
`;

const ProductNameButton = styled.button`
  display: inline-flex;
  max-width: 100%;
  padding: 0;
  border: 0;
  background: transparent;
  color: #111827;
  font-weight: 700;
  text-align: left;
  cursor: pointer;

  &:hover {
    color: #2867f5;
  }
`;

const EditorShell = styled.div`
  display: grid;
  grid-template-columns: 260px minmax(0, 1fr);
  min-height: 620px;
  border: 1px solid rgba(226, 232, 240, 0.92);
  border-radius: 8px;
  overflow: hidden;
  background: rgba(255, 255, 255, 0.88);
  box-shadow: 0 8px 26px rgba(15, 23, 42, 0.05);

  @media (max-width: 920px) {
    grid-template-columns: 1fr;
  }
`;

const StepRail = styled.div`
  padding: 18px;
  border-right: 1px solid #e2e8f0;
  background: #f8fafc;

  @media (max-width: 920px) {
    border-right: 0;
    border-bottom: 1px solid #e2e8f0;
  }
`;

const StepContent = styled.div`
  min-width: 0;
  padding: 24px;

  .ant-typography h1,
  h1.ant-typography {
    font-size: 24px;
    line-height: 1.25;
  }
`;

const CompactPanel = styled.div`
  border: 1px solid #e2e8f0;
  border-radius: 8px;
  padding: 18px;
  background: #fff;
`;

const MetricGrid = styled.div`
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(140px, 1fr));
  gap: 10px;
`;

const MetricItem = styled.div`
  padding: 12px;
  border: 1px solid #e2e8f0;
  border-radius: 8px;
  background: #f8fafc;
`;

const getQueryValue = (value: string | string[] | undefined) =>
  Array.isArray(value) ? value[0] : value;

const formatDataSource = (type?: string) =>
  type
    ? type
        .toLowerCase()
        .split('_')
        .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
        .join(' ')
    : 'Not connected';

const formatDate = (value?: string | null) => {
  if (!value) return 'Not available';
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return value;
  return date.toISOString().slice(0, 10);
};

const getDataSourceName = (properties?: Record<string, unknown>) => {
  if (!properties) return 'WrenAI data product';
  return (
    (properties.displayName as string) ||
    (properties.name as string) ||
    (properties.database as string) ||
    (properties.databaseName as string) ||
    (properties.projectId as string) ||
    'WrenAI data product'
  );
};

const getCurrentStep = ({
  hasSource,
  modelCount,
  deployStatus,
}: {
  hasSource: boolean;
  modelCount: number;
  deployStatus?: string;
}) => {
  if (!hasSource) return 'source';
  if (modelCount === 0) return 'tables';
  if (deployStatus === 'SYNCED') return 'ask';
  return 'publish';
};

const relationsToInput = (
  relationsData: SelectedRecommendRelations,
): RelationInput[] =>
  Object.entries(relationsData).reduce<RelationInput[]>(
    (acc, [_modelName, relations]) => [
      ...acc,
      ...relations.map((relation) => ({
        fromModelId: Number(relation.fromField.modelId),
        fromColumnId: Number(relation.fromField.fieldId),
        toModelId: Number(relation.toField.modelId),
        toColumnId: Number(relation.toField.fieldId),
        type: relation.type,
      })),
    ],
    [],
  );

const buildRecommendRelations = (autoGenerateRelation = []) =>
  autoGenerateRelation.reduce(
    (acc, currentValue) => {
      const { displayName, referenceName, relations } = currentValue;
      acc.recommendRelations[referenceName] = (relations || []).map(
        (relation) => ({
          name: relation.name,
          fromField: {
            modelId: String(relation.fromModelId),
            modelName: relation.fromModelReferenceName,
            fieldId: String(relation.fromColumnId),
            fieldName: relation.fromColumnReferenceName,
          },
          toField: {
            modelId: String(relation.toModelId),
            modelName: relation.toModelReferenceName,
            fieldId: String(relation.toColumnId),
            fieldName: relation.toColumnReferenceName,
          },
          type: relation.type,
          isAutoGenerated: true,
        }),
      );
      acc.recommendNameMapping[referenceName] = displayName;
      return acc;
    },
    {
      recommendRelations: {},
      recommendNameMapping: {},
    } as {
      recommendRelations: SelectedRecommendRelations;
      recommendNameMapping: Record<string, string>;
    },
  );

export default function Database() {
  const router = useRouter();
  const mode = getQueryValue(router.query.mode);
  const isCreating = mode === 'new';
  const isEditing = mode === 'edit';
  const isEditorMode = isCreating || isEditing;
  const queryStep = getQueryValue(router.query.step) as EditorStep | undefined;
  const settingsQuery = useGetSettingsQuery({
    fetchPolicy: 'cache-and-network',
  });
  const diagramQuery = useDiagramQuery({ fetchPolicy: 'cache-and-network' });
  const deployStatusQuery = useDeployStatusQuery({
    fetchPolicy: 'cache-and-network',
    pollInterval: 2500,
  });

  const dataSource = settingsQuery.data?.settings?.dataSource;
  const dataSourceType = dataSource?.type;
  const hasSource = Boolean(dataSourceType);
  const schemaChangeQuery = useSchemaChangeQuery({
    fetchPolicy: 'cache-and-network',
    skip: !hasSource || isEditorMode,
  });
  const models = diagramQuery.data?.diagram?.models || [];
  const views = diagramQuery.data?.diagram?.views || [];
  const modelCount = models.length;
  const fieldCount = models.reduce(
    (sum, model) => sum + (model?.fields?.length || 0),
    0,
  );
  const relationshipCount = models.reduce(
    (sum, model) => sum + (model?.relationFields?.length || 0),
    0,
  );
  const deployStatus = deployStatusQuery.data?.modelSync?.status;
  const lastSchemaChangeTime =
    schemaChangeQuery.data?.schemaChange?.lastSchemaChangeTime;
  const productName = getDataSourceName(dataSource?.properties);
  const suggestedStep = getCurrentStep({ hasSource, modelCount, deployStatus });
  const activeStep: EditorStep = editorStepKeys.includes(queryStep)
    ? queryStep
    : suggestedStep;
  const activeStepIndex = editorSteps.findIndex(
    (step) => step.key === activeStep,
  );
  const [selectedDataSource, setSelectedDataSource] =
    useState<DataSourceName>();
  const [connectError, setConnectError] = useState<Record<string, any>>(null);

  const tablesQuery = useListDataSourceTablesQuery({
    fetchPolicy: 'no-cache',
    skip: !hasSource || activeStep !== 'tables',
  });
  const relationsQuery = useAutoGeneratedRelationsQuery({
    fetchPolicy: 'no-cache',
    skip: modelCount === 0 || activeStep !== 'access',
  });

  const [saveDataSourceMutation, saveDataSourceResult] =
    useSaveDataSourceMutation({
      refetchQueries: ['GetSettings'],
      awaitRefetchQueries: true,
    });
  const [updateDataSourceMutation, updateDataSourceResult] =
    useUpdateDataSourceMutation({
      refetchQueries: ['GetSettings'],
      awaitRefetchQueries: true,
    });
  const [saveTablesMutation, saveTablesResult] = useSaveTablesMutation({
    refetchQueries: [{ query: DIAGRAM }, { query: LIST_MODELS }],
    awaitRefetchQueries: true,
  });
  const [saveRelationsMutation, saveRelationsResult] = useSaveRelationsMutation(
    {
      refetchQueries: [{ query: DIAGRAM }],
      awaitRefetchQueries: true,
    },
  );

  const recommendRelationsResult = useMemo(
    () => buildRecommendRelations(relationsQuery.data?.autoGenerateRelation),
    [relationsQuery.data?.autoGenerateRelation],
  );

  const setEditorStep = (
    step: EditorStep,
    nextMode = isCreating ? 'new' : 'edit',
  ) => {
    router.push(
      {
        pathname: Path.Database,
        query: { mode: nextMode, step },
      },
      undefined,
      { shallow: true },
    );
  };

  const openEditor = (step: EditorStep = suggestedStep) => {
    router.push(
      {
        pathname: Path.Database,
        query: { mode: 'edit', step },
      },
      undefined,
      { shallow: true },
    );
  };

  const openNewProduct = () => {
    setSelectedDataSource(undefined);
    setConnectError(null);
    router.push(
      {
        pathname: Path.Database,
        query: { mode: 'new', step: 'source' },
      },
      undefined,
      { shallow: true },
    );
  };

  const backToList = () => {
    setSelectedDataSource(undefined);
    setConnectError(null);
    router.push(Path.Database, undefined, { shallow: true });
  };

  const onSourceNext = async (data: {
    dataSource?: DataSourceName;
    properties?: Record<string, any>;
  }) => {
    if (data.dataSource) {
      setSelectedDataSource(data.dataSource);
      setConnectError(null);
      return;
    }
    const type = isCreating
      ? selectedDataSource
      : selectedDataSource || dataSourceType;
    if (!type) return;

    try {
      setConnectError(null);
      const properties = transformFormToProperties(data.properties, type);
      if (isEditing && hasSource) {
        await updateDataSourceMutation({
          variables: { data: { properties } },
        });
      } else {
        await saveDataSourceMutation({
          variables: { data: { type, properties } },
        });
      }
      message.success('Data source saved.');
      setSelectedDataSource(undefined);
      setEditorStep('tables', 'edit');
    } catch (error) {
      setConnectError(parseGraphQLError(error as any));
    }
  };

  const onSaveTables = async (data: { selectedTables: string[] }) => {
    await saveTablesMutation({
      variables: { data: { tables: data.selectedTables } },
    });
    message.success('Tables saved.');
    setEditorStep('access');
  };

  const onSaveRelations = async (data: {
    relations: SelectedRecommendRelations;
  }) => {
    const relations = relationsToInput(data.relations);
    if (relations.length > 0) {
      await saveRelationsMutation({ variables: { data: { relations } } });
    }
    message.success('Access and relationships saved.');
    setEditorStep('modeling');
  };

  const renderProductList = () => (
    <>
      <ConstructToolbar
        left={
          <>
            <Tag>{hasSource ? '1 data product' : '0 data products'}</Tag>
            {hasSource && <Tag>{formatDataSource(dataSourceType)}</Tag>}
          </>
        }
        right={<Button onClick={() => settingsQuery.refetch()}>Refresh</Button>}
      />

      {hasSource ? (
        <ProductRow>
          <div>
            <ProductNameButton onClick={() => openEditor(suggestedStep)}>
              {productName}
            </ProductNameButton>
            <div className="gray-7 text-sm mt-1">
              Current WrenAI semantic project
            </div>
          </div>
          <StatusTag status={deployStatus || 'not deployed'} />
          <Tag icon={<DatabaseOutlined />}>
            {formatDataSource(dataSourceType)}
          </Tag>
          <Text className="gray-8">{formatDate(lastSchemaChangeTime)}</Text>
          <Space>
            <Button
              size="small"
              icon={<EditOutlined />}
              onClick={() => openEditor(suggestedStep)}
            >
              Edit
            </Button>
            <Link href={Path.Home}>
              <Button size="small" type="primary">
                Ask
              </Button>
            </Link>
          </Space>
        </ProductRow>
      ) : (
        <ConstructEmpty
          title="No data products"
          description="Create a data product from a real WrenAI datasource. Multi-product isolation is not mocked in this frontend."
          action={
            <Button
              type="primary"
              icon={<PlusOutlined />}
              onClick={openNewProduct}
            >
              New data product
            </Button>
          }
        />
      )}
    </>
  );

  const renderSourceStep = () => {
    const typeForForm = (isCreating
      ? selectedDataSource
      : selectedDataSource || dataSourceType) as unknown as
      | DATA_SOURCES
      | undefined;
    const initialValues =
      isEditing && hasSource && dataSourceType
        ? transformPropertiesToForm(
            dataSource?.properties || {},
            dataSourceType,
          )
        : undefined;

    if (!typeForForm) {
      return (
        <Starter
          submitting={
            saveDataSourceResult.loading || updateDataSourceResult.loading
          }
          onNext={onSourceNext}
        />
      );
    }

    return (
      <ConnectDataSource
        dataSource={typeForForm}
        initialValues={initialValues}
        mode={isEditing && hasSource ? FORM_MODE.EDIT : FORM_MODE.CREATE}
        connectError={connectError}
        submitting={
          saveDataSourceResult.loading || updateDataSourceResult.loading
        }
        submitText={isEditing && hasSource ? 'Save and continue' : 'Connect'}
        onBack={() => {
          if (selectedDataSource && isCreating) {
            setSelectedDataSource(undefined);
          } else {
            backToList();
          }
        }}
        onNext={onSourceNext}
      />
    );
  };

  const renderTablesStep = () => {
    if (!hasSource) {
      return (
        <Alert
          type="info"
          showIcon
          message="Connect a data source first"
          action={<Button onClick={() => setEditorStep('source')}>Open</Button>}
        />
      );
    }
    return (
      <SelectModels
        fetching={tablesQuery.loading}
        tables={tablesQuery.data?.listDataSourceTables || []}
        submitting={saveTablesResult.loading}
        onBack={() => setEditorStep('source', 'edit')}
        onNext={onSaveTables}
      />
    );
  };

  const renderAccessStep = () => {
    if (modelCount === 0) {
      return (
        <Alert
          type="info"
          showIcon
          message="Select tables before configuring relationships"
          action={<Button onClick={() => setEditorStep('tables')}>Open</Button>}
        />
      );
    }
    return (
      <DefineRelations
        fetching={relationsQuery.loading}
        {...recommendRelationsResult}
        submitting={saveRelationsResult.loading}
        onBack={() => setEditorStep('tables', 'edit')}
        onNext={onSaveRelations}
        onSkip={() => setEditorStep('modeling')}
      />
    );
  };

  const renderModelingStep = () => (
    <Row gutter={[16, 16]}>
      <Col xs={24} lg={14}>
        <CompactPanel>
          <MetricGrid>
            {[
              { label: 'Models', value: modelCount },
              { label: 'Fields', value: fieldCount },
              { label: 'Relationships', value: relationshipCount },
              { label: 'Views', value: views.length },
            ].map((item) => (
              <MetricItem key={item.label}>
                <div className="gray-7 text-sm">{item.label}</div>
                <div className="gray-10 text-lg text-bold mt-1">
                  {item.value}
                </div>
              </MetricItem>
            ))}
          </MetricGrid>
        </CompactPanel>
      </Col>
      <Col xs={24} lg={10}>
        <CompactPanel>
          <Paragraph className="gray-7 mb-4">
            Modeling uses WrenAI's full semantic canvas. It stays in the data
            product journey and opens the production modeling surface.
          </Paragraph>
          <Link href={Path.Modeling}>
            <Button type="primary" icon={<ConsoleSqlOutlined />}>
              Open semantic modeling
            </Button>
          </Link>
        </CompactPanel>
      </Col>
    </Row>
  );

  const renderKnowledgeStep = () => (
    <ConstructGrid>
      <ConstructCard
        icon={<FunctionOutlined />}
        title="Question-SQL pairs"
        description="Curated examples that teach the data product how your team asks and writes SQL."
        footer={
          <Link href={Path.KnowledgeQuestionSQLPairs}>
            <Button size="small">Open</Button>
          </Link>
        }
      />
      <ConstructCard
        icon={<FunctionOutlined />}
        title="Instructions"
        description="Business rules and SQL generation guidance attached to this WrenAI project."
        footer={
          <Link href={Path.KnowledgeInstructions}>
            <Button size="small">Open</Button>
          </Link>
        }
      />
    </ConstructGrid>
  );

  const renderPublishStep = () => (
    <Row gutter={[16, 16]}>
      <Col xs={24} lg={12}>
        <CompactPanel>
          <Space direction="vertical" size={8}>
            <Text strong>Deployment status</Text>
            <StatusTag status={deployStatus || 'not deployed'} />
            <Text className="gray-7 text-sm">
              WrenAI deploys semantic changes through the existing modeling and
              API management pipeline.
            </Text>
          </Space>
        </CompactPanel>
      </Col>
      <Col xs={24} lg={12}>
        <CompactPanel>
          <Space direction="vertical" size={12}>
            <Text strong>Publish history</Text>
            <Link href={Path.APIManagementHistory}>
              <Button icon={<ApiOutlined />}>Open history</Button>
            </Link>
          </Space>
        </CompactPanel>
      </Col>
    </Row>
  );

  const renderAskStep = () => (
    <CompactPanel>
      <Space direction="vertical" size={12}>
        <Text strong>Runtime</Text>
        <Text className="gray-7">
          Ask opens WrenAI's GenBI conversation surface for this data product.
        </Text>
        <Link href={Path.Home}>
          <Button type="primary">Ask this data product</Button>
        </Link>
      </Space>
    </CompactPanel>
  );

  const renderEditorStep = () => {
    switch (activeStep) {
      case 'source':
        return renderSourceStep();
      case 'tables':
        return renderTablesStep();
      case 'access':
        return renderAccessStep();
      case 'modeling':
        return renderModelingStep();
      case 'knowledge':
        return renderKnowledgeStep();
      case 'publish':
        return renderPublishStep();
      case 'ask':
        return renderAskStep();
      default:
        return null;
    }
  };

  const renderEditor = () => (
    <>
      <ConstructToolbar
        left={
          <>
            <Button icon={<ArrowLeftOutlined />} onClick={backToList}>
              Data products
            </Button>
            {hasSource && <Tag>{productName}</Tag>}
          </>
        }
        right={
          hasSource && (
            <Link href={Path.Home}>
              <Button type="primary">Ask</Button>
            </Link>
          )
        }
      />
      <EditorShell>
        <StepRail>
          <Steps
            direction="vertical"
            size="small"
            current={activeStepIndex}
            onChange={(index) => setEditorStep(editorSteps[index].key)}
          >
            {editorSteps.map((step) => (
              <Steps.Step key={step.key} title={step.title} icon={step.icon} />
            ))}
          </Steps>
        </StepRail>
        <StepContent>
          <Spin spinning={settingsQuery.loading || diagramQuery.loading}>
            {renderEditorStep()}
          </Spin>
        </StepContent>
      </EditorShell>
    </>
  );

  return (
    <ConstructLayout
      activeKey="database"
      icon={<ConsoleSqlOutlined />}
      title="Database"
      description="Data products"
      loading={settingsQuery.loading && !settingsQuery.data}
      actions={
        isEditorMode ? (
          <Button icon={<ArrowLeftOutlined />} onClick={backToList}>
            Back
          </Button>
        ) : (
          <Button
            type="primary"
            icon={<PlusOutlined />}
            onClick={openNewProduct}
          >
            New data product
          </Button>
        )
      }
    >
      {isEditorMode ? renderEditor() : renderProductList()}
    </ConstructLayout>
  );
}
